//! Core domain models for the Deterministic Exchange Core (DEC).
//!
//! To achieve sub-microsecond matching latency, these structures are designed to:
//! 1. Be `no_std` compatible, avoiding any dynamic memory allocation (`std::vec` or `std::string`) in the hot path.
//! 2. Use `#[repr(C)]` layout and have explicit padding fields to ensure structure density and prevent compiler alignment gaps.
//! 3. Support zero-copy casting to/from raw byte slices directly, avoiding parsing overhead when interacting with the Write-Ahead Log (WAL).
//! 4. Use primitive fixed-point types for price and quantity to eliminate non-deterministic floating-point math and rounding errors.

use core::fmt;

/// The side of an order.
/// Using a type-safe enum with explicit `u8` representation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum Side {
    /// Buy / Bid side
    Buy = 0,
    /// Sell / Ask side
    Sell = 1,
}

impl Side {
    /// Deserializes a raw `u8` to a type-safe `Side`.
    /// 
    /// # Errors
    /// Returns `Err(())` if the byte value does not map to a valid `Side`.
    #[inline]
    pub const fn from_raw(raw: u8) -> Result<Self, ()> {
        match raw {
            0 => Ok(Side::Buy),
            1 => Ok(Side::Sell),
            _ => Err(()),
        }
    }

    /// Converts the `Side` to its opposite side.
    /// Used inside the matching loop to determine match crossover.
    #[inline]
    pub const fn opposite(self) -> Self {
        match self {
            Side::Buy => Side::Sell,
            Side::Sell => Side::Buy,
        }
    }
}

/// Core Order structure.
/// 
/// Alignment and padding are carefully managed to ensure the struct is packed
/// exactly to 40 bytes with no compiler-inserted hidden padding. This prevents
/// undefined behavior when casting raw byte buffers via zero-copy.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(C)]
pub struct Order {
    /// Globally unique order ID generated by the Sequencer.
    /// Assumptions: Must be monotonically increasing and non-zero.
    pub order_id: u64,

    /// Fixed-point price representation.
    /// Assumptions: Pre-scaled by a factor of 10,000 (4 decimal places). 
    /// Range: 1 to `u64::MAX`. A price of 0 is considered invalid.
    pub price: u64,

    /// Remaining quantity to match.
    /// Assumptions: Pre-scaled by a factor of 10,000.
    /// Range: 0 to `u64::MAX`. If quantity reaches 0, the order is filled and removed.
    pub quantity: u64,

    /// Unique identifier of the client entity originating the order.
    /// Used by the compliance engine to check for Wash Trading violations.
    pub client_id: u64,

    /// Raw representation of the order side (0 = Buy, 1 = Sell).
    pub raw_side: u8,

    /// Reserved padding bytes to align the structure size to a multiple of 8 bytes.
    /// Explicitly declared to avoid compiler-specific alignment gaps which break zero-copy safety.
    pub _padding: [u8; 7],
}

impl Order {
    /// Creates a new `Order` instance.
    #[inline]
    pub const fn new(order_id: u64, price: u64, quantity: u64, client_id: u64, side: Side) -> Self {
        Self {
            order_id,
            price,
            quantity,
            client_id,
            raw_side: side as u8,
            _padding: [0; 7],
        }
    }

    /// Helper to get the type-safe `Side`.
    #[inline]
    pub fn side(&self) -> Side {
        Side::from_raw(self.raw_side).unwrap_or(Side::Buy)
    }

    /// Safely casts a byte slice to an `Order` reference without copying.
    /// Validates length and memory alignment to prevent undefined behavior.
    #[inline]
    pub fn from_bytes(bytes: &[u8]) -> Option<&Self> {
        if bytes.len() < core::mem::size_of::<Self>() {
            return None;
        }
        let ptr = bytes.as_ptr();
        // Check alignment is a multiple of 8 (since fields are u64)
        if (ptr as usize) % core::mem::align_of::<Self>() != 0 {
            return None;
        }
        unsafe { Some(&*(ptr as *const Self)) }
    }

    /// Casts the `Order` to an immutable raw byte slice.
    #[inline]
    pub fn as_bytes(&self) -> &[u8] {
        unsafe {
            core::slice::from_raw_parts(
                self as *const Self as *const u8,
                core::mem::size_of::<Self>(),
            )
        }
    }
}

/// A match event representing a single filling intersection between a Maker order and a Taker order.
/// 
/// Generated inside the matching loop. This structure is transient and is recycled
/// using pre-allocated buffers to prevent allocation pressure.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(C)]
pub struct Match {
    /// Unique ID of the pre-existing order resting in the book.
    pub maker_id: u64,

    /// Unique ID of the aggressive incoming order.
    pub taker_id: u64,

    /// Execution price of the match (fixed-point, scaled by 10,000).
    pub price: u64,

    /// Number of shares/contracts filled (fixed-point, scaled by 10,000).
    pub quantity: u64,
}

impl Match {
    /// Safely casts a byte slice to a `Match` reference.
    #[inline]
    pub fn from_bytes(bytes: &[u8]) -> Option<&Self> {
        if bytes.len() < core::mem::size_of::<Self>() {
            return None;
        }
        let ptr = bytes.as_ptr();
        if (ptr as usize) % core::mem::align_of::<Self>() != 0 {
            return None;
        }
        unsafe { Some(&*(ptr as *const Self)) }
    }

    /// Casts the `Match` to an immutable raw byte slice.
    #[inline]
    pub fn as_bytes(&self) -> &[u8] {
        unsafe {
            core::slice::from_raw_parts(
                self as *const Self as *const u8,
                core::mem::size_of::<Self>(),
            )
        }
    }
}

/// An immutable record of a completed trade, persistently tied to the sequence ID that triggered it.
/// 
/// Designed to be written to the transaction audit stream.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(C)]
pub struct Trade {
    /// Monotonically increasing trade execution ID.
    pub trade_id: u64,

    /// The Sequencer ID of the aggressive order that triggered this trade.
    /// This provides strict auditability to match every trade back to its original event.
    pub sequence_id: u64,

    /// The order ID of the maker side.
    pub maker_id: u64,

    /// The order ID of the taker side.
    pub taker_id: u64,

    /// Execution price (fixed-point, scaled by 10,000).
    pub price: u64,

    /// Execution quantity (fixed-point, scaled by 10,000).
    pub quantity: u64,

    /// Raw representation of the taker side (0 = Buy, 1 = Sell).
    pub raw_side: u8,

    /// Reserved padding bytes to align the structure size to 56 bytes.
    pub _padding: [u8; 7],
}

impl Trade {
    /// Creates a new `Trade` instance.
    #[inline]
    pub const fn new(
        trade_id: u64,
        sequence_id: u64,
        maker_id: u64,
        taker_id: u64,
        price: u64,
        quantity: u64,
        side: Side,
    ) -> Self {
        Self {
            trade_id,
            sequence_id,
            maker_id,
            taker_id,
            price,
            quantity,
            raw_side: side as u8,
            _padding: [0; 7],
        }
    }

    /// Helper to get the type-safe `Side`.
    #[inline]
    pub fn side(&self) -> Side {
        Side::from_raw(self.raw_side).unwrap_or(Side::Buy)
    }

    /// Safely casts a byte slice to a `Trade` reference.
    #[inline]
    pub fn from_bytes(bytes: &[u8]) -> Option<&Self> {
        if bytes.len() < core::mem::size_of::<Self>() {
            return None;
        }
        let ptr = bytes.as_ptr();
        if (ptr as usize) % core::mem::align_of::<Self>() != 0 {
            return None;
        }
        unsafe { Some(&*(ptr as *const Self)) }
    }

    /// Casts the `Trade` to an immutable raw byte slice.
    #[inline]
    pub fn as_bytes(&self) -> &[u8] {
        unsafe {
            core::slice::from_raw_parts(
                self as *const Self as *const u8,
                core::mem::size_of::<Self>(),
            )
        }
    }
}

impl fmt::Display for Order {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "Order(id: {}, side: {:?}, price: {}, qty: {})",
            self.order_id,
            self.side(),
            self.price,
            self.quantity
        )
    }
}

impl fmt::Display for Match {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "Match(maker: {}, taker: {}, price: {}, qty: {})",
            self.maker_id, self.taker_id, self.price, self.quantity
        )
    }
}

impl fmt::Display for Trade {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "Trade(id: {}, seq: {}, maker: {}, taker: {}, side: {:?}, price: {}, qty: {})",
            self.trade_id,
            self.sequence_id,
            self.maker_id,
            self.taker_id,
            self.side(),
            self.price,
            self.quantity
        )
    }
}
